### ISSUE TITLE
Ссылки в профиле спикера

### ISSUE THREAD

**Issue by kirkkonen** [kromkrom/NetForSpeech#15]
ИМХО, нужно в профиле спикера указывать ссылки на его персональные и публичные страницы в соцсетях. Стоит даже завести отельные графы типа Твиттер, Фейсбук, Линкд ин, Вконтакте, Инстаграм.

**Comment by kirill-gr** [comment]
Вот прям для каждой соцсети свою ссылку иметь или просто список "личные ресурсы"?

**Comment by kirkkonen** [comment]
Я бы для каждой сделал.

**Comment by kirill-gr** [comment]
в реальности всяких таких соц сетей достаточно много в разных регионах. с ходу в латинской америке не будет вэкашечки, зато будет оркут (http://blog.wordbank.com/wp-content/uploads/2011/10/2web.bbdodigital.cl-download-Latin_America_Social_Networking_Study_2011_Final_English.pdf.png). нахрена всем латимерским спикерами иметь поле "ВК" со значением "нет", а всем европейским - поле "оркут" со значением "нет"?

**Comment by kirill-gr** [comment]
хотя, конечно, сейчас ситуация меняется. я посмотрел, так этот когда-то популярный сервис уже 4 месяца как закрыт

**Comment by kirkkonen** [comment]
Еще раз, а кто мешает для определенных регионов просто закрывать в админке определенный пункт? Ну не сидит у нас народ в Байду, да и хрен с ней. А спецом для китайцев сделаем. Вопрос, что делать с энейблом/дизейблом... Может быть, сделать список интернациональных соцсетей, а потом, под катом, выдавать список национальных. Не может же там быть 100500 этих сетей.

**Comment by kirill-gr** [comment]
Ладно, давай так сформулируем вопрос:  
ты обязательно хочешь, чтобы при редактировании была "сетка" из возможных социальных сетей и полей для ввода ссылок, а при просмотре - тоже самое, но только не поля для ввода, а сами ссылки и там где нет ссылки - явным образом указано, что профиля "нет"  
или тебя устроит, чтобы при редактировании можно было добавить любое количество ссылок, при этом в выпадающем меню был бы выбор соцсети, а при просмотре отображался список только тех соцсетей, на которые есть ссылки?

**Comment by kirkkonen** [comment]
Второй вариант выглядит рациональнее.

**Comment by kirill-gr** [comment]
я тебе его и предлагаю ;)

**Comment by kirkkonen** [comment]
Ну, так и сделаем :)

**Comment by kirill-gr** [comment]
Добавляем к перечню полей спикера поле "Личные ресурсы". "Личный ресурс" имеет тип (ВК, ФБ, Твиттер, ..., прочее) и url.
По делу урл нужно нарезать и склеивать автоматически, но это потом (см. #17).

**Comment by kirill-gr** [comment]
Добавил в простеньком варианте. Можно потестить.

**Comment by kirkkonen** [comment]
Уже-с!
