### ISSUE TITLE
Добавить факт в базу

### ISSUE THREAD

**Issue by kirill-gr** [kromkrom/NetForSpeech#2]
Кейс: [UC1_A]

**Суть**
Контрибьютор должен добавлять факты в базу

**Требования**
Поля факта:
- суть факта
- ссылка на СМИ
- дата и время публикации
- название СМИ

**Приёмка**
1. Форма добавления
Пусть пользователь находится на странице добавления факта
Тогда на странице должна присутствовать форма добавления факта со всеми полями
2. Валидность факта
Пусть пользователь добавляет факт
Если введены все данные о факте
Тогда факт добавлен
Если не все данные введены
Тогда показано сообщение об ошибке

**Comment by kirkkonen** [comment]
Все данные о факте - это ссылка, дата/время и название СМИ, я правильно понимаю?

**Comment by kirill-gr** [comment]
Все данные, которые на момент выполнения теста будут у факта.
По мере разработки формулировка приёмочного теста скорее всего изменится. Возможно, там будет указано, какие поля являются обязательными. На данный момент приёмочный тест описан так, чтобы считать вот эту простенькую историю выполненной.

**Comment by kirill-gr** [comment]
Можно тестировать!

**Comment by kirill-gr** [comment]
Выполнено
