### ISSUE TITLE
Добавить спикера

### ISSUE THREAD

**Issue by kirill-gr** [kromkrom/NetForSpeech#6]
Кейс: [UC2_A]

**Суть**
Модератор должен добавлять спикеров в базу

**Требования**
Спикер имеет:
- Главное имя (например, фамилия) (обязательно)
- Вторичное имя (например, имя)
- Другие имена (например, отчество)
- Дата рождения
- Места работы (текущие и прошлые)

**Приёмка**
1. Форма добавления
Пусть пользователь находится на странице добавления спикера
Тогда на странице должна присутствовать форма добавления спикера со всеми полями
2. Валидность спикера
Пусть пользователь добавляет спикера
Если введены все обязательные данные о спикере
Тогда спикер добавлен
Если не все данные введены
Тогда показано сообщение об ошибке

**Comment by kirill-gr** [comment]
Ты уверен, что мы хотим именно имя-фамилия-другие_имена схему?
http://habrahabr.ru/post/130361/
Можно ограничиться одним полем, а потом, когда заняться нечем будет, прикрутить выбор схемы (ИОФ, ИФ, ИО, ИДФ и т.д.) и умную сортировку?

**Comment by kirill-gr** [comment]
Почитав пост я предлагаю схему:
1. Фамилия (или другое основное имя)
2. Остальная часть имени
3. Полное имя при рождении

**Comment by kirkkonen** [comment]
Че-то наворочено. Давай предусмотрим третье поле, но активируем для тех стран, где это актуально, м? Для Раши точно не актуально ведь.

**Comment by kirill-gr** [comment]
Для Раши, конечно, неактуально. Но если ты почитаешь пост (а лучше оригинал http://www.w3.org/International/questions/qa-personal-names), то поймёшь, что со схемой First Name + Last Name + Other Name мы будем достаточно ограничены регионами, где Last Name - это основное поле для сортировки и поиска.
Т.е. я в первую очередь говорю о том, что важно различать именно это:
- имя, по которому сортируют и ищут
- остальные имена

На счёт полного имени я, пожалуй, перебрал для начала, но в целом предыдущие имена могут быть актуальны.

**Comment by kirill-gr** [comment]
"Место проживания" убрал
