### ISSUE TITLE
Добавить высказывание

### ISSUE THREAD

**Issue by kirkkonen** [kromkrom/NetForSpeech#7]
Кейс: [UC1_B]

**Суть**
Пользователь может добавить высказывание в базу

**Требования**
Высказывание имеет:
- Текст (обязательно)
- Тему
- Ссылку на спикера (обязательно)
- Дату (обязательно)
- Время 
- Канал коммуникации
- Название опубликовавшего СМИ (обязательно)
- Ссылку на страницу с опубликованной новостью (обязательно)

**Приемка**
1. Форма добавления
Пусть пользователь находится на странице добавления высказывания
Тогда на странице должна быть форма добавления высказывания со всеми полями
2. Валидность высказывания
Пусть пользователь добавляет высказывание
Если введены все обязательные данные
Тогда высказывание добавлено
Если не все данные введены
Тогда показано сообщение об ошибке

**Comment by kirill-gr** [comment]
1. В последствии "место высказывания", наверное, стоит сделать отдельным объектом. Что-нибудь типа "событие" (встреча, выступление, интервью, колонка..?)
2. Предлагаю на этой итерации (для простоты) ссылки на другие факты и высказывания не делать

**Comment by kirill-gr** [comment]
А ещё я не вижу ссылки на спикера. Упущено?

**Comment by kirkkonen** [comment]
1. Согласен
2. Согласен
3. Именно  :) Торопился сильно

**Comment by kirill-gr** [comment]
Заменил "Место высказывания" на "Канал коммуникации".
Под этим подразумевается условия, а точнее способ (речь, выступление, интервью, колонка, ...) и место (встреча, СМИ, прямая линия, ...) передачи высказывания.
